export const POST_MOTHER_SCHOOL_PHOTOS = 'POST_MOTHER_SCHOOL_PHOTOS';
export const POST_MOTHER_SCHOOL_PHOTOS_ING = 'POST_MOTHER_SCHOOL_PHOTOS_ING';
export const POST_MOTHER_SCHOOL_PHOTOS_SUCCESS = 'POST_MOTHER_SCHOOL_PHOTOS_SUCCESS';
export const POST_MOTHER_SCHOOL_PHOTOS_FAIL = 'POST_MOTHER_SCHOOL_PHOTOS_FAIL';

export const POST_MOTHER_SCHOOL_WISHES = 'POST_MOTHER_SCHOOL_WISHES';