// 获取作品
export const POST_EXHIBITIONS = 'POST_EXHIBITIONS';
export const POST_EXHIBITIONS_ING = 'POST_EXHIBITIONS_ING';
export const POST_EXHIBITIONS_SUCCESS = 'POST_EXHIBITIONS_SUCCESS';
export const POST_EXHIBITIONS_FAIL = 'POST_EXHIBITIONS_FAIL';

// 搜索作品
export const POST_SEARCH_EXHIBITIONS = 'POST_SEARCH_EXHIBITIONS';
export const POST_SEARCH_EXHIBITIONS_ING = 'POST_SEARCH_EXHIBITIONS_ING';
export const POST_SEARCH_EXHIBITIONS_SUCCESS = 'POST_SEARCH_EXHIBITIONS_SUCCESS';
export const POST_SEARCH_EXHIBITIONS_FAIL = 'POST_SEARCH_EXHIBITIONS_FAIL';

// 作品点赞
export const POST_VOTE = 'POST_VOTE';
export const POST_VOTE_ING = 'POST_VOTE_ING';
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';
export const POST_VOTE_FAIL = 'POST_VOTE_FAIL';