export const POST_EXHIBITIONS = 'POST_EXHIBITIONS';
export const POST_EXHIBITIONS_ING = 'POST_EXHIBITIONS_ING';
export const POST_EXHIBITIONS_SUCCESS = 'POST_EXHIBITIONS_SUCCESS';
export const POST_EXHIBITIONS_FAIL = 'POST_EXHIBITIONS_FAIL';
